# Generated by Django 2.1.2 on 2018-11-03 18:54

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('rated', models.CharField(max_length=63)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=63)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=31), size=None)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=1023)),
                ('plot', models.TextField()),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=31), size=None)),
                ('country', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=31), size=None)),
                ('awards', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('ratings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metascore', models.IntegerField()),
                ('imdb_rating', models.CharField(max_length=63)),
                ('imdb_votes', models.IntegerField()),
                ('type', models.CharField(max_length=63)),
                ('dvd', models.DateField()),
                ('box_office', models.CharField(max_length=63)),
                ('production', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
